services:
  image-processor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - fashion_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - .:/app
      - model-cache:/root/.cache/torch/hub
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=https://fashion.aknevrnky.dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_AUTH_TOKEN=fashion-api-token-2025
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.image-processor.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.image-processor.entrypoints=web"
      - "traefik.http.routers.image-processor.service=image-processor"
      - "traefik.http.services.image-processor.loadbalancer.server.port=8000"
      - "traefik.http.services.image-processor.loadbalancer.server.scheme=http"

  celery-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A app.celery_config.celery_app worker --loglevel=info --concurrency=4
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    depends_on:
      - redis
    volumes:
      - .:/app
      - model-cache:/root/.cache/torch/hub
    environment:
      - API_BASE_URL=https://fashion.aknevrnky.dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - fashion_network
    labels:
      - "traefik.enable=false"

  redis:
    image: 'redis:alpine'
    volumes:
      - 'image-processor-redis:/data'
    networks:
      - fashion_network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    labels:
      - "traefik.enable=false"

networks:
  fashion_network:
    external: true

volumes:
  image-processor-redis:
  model-cache:
